### ISSUE TITLE
Milan 2017 - Participation Percentage and Tournament Strength should be adjusted

### ISSUE THREAD

**Issue by nashmani** [mcekovic/tennis-crystal-ball#233]
PP & TS for Milan 2017 are 10.0% | 442 while it should be much higher. It should take into account only the #NextGenATP players who were eligible for the tournament. The stats should be close to that of Tour Finals 2017

**Comment by mcekovic** [comment]
Participation percentage and strength measure how much tournament is entered by top players and how hard is to win the tournament. Regardless if rules for tournament entry are different for this tournament, participation and strength must use the same formula as for other tournaments, in order that we can compare it by participation and strength with other tournaments.
