### ISSUE TITLE
Player Profile / Matches updates (fixes)

### ISSUE THREAD

**Issue by pedja-d** [mcekovic/tennis-crystal-ball#25]
1. Looks like "Vs..." filter is using Seed instead of Rank for the players ... Rank may be more important (best is to have them both as separate filters)
2. It will be nice to have a filter for "Wins / Looses" so one can easily get, for example, all Rafa's looses on Clay

**Comment by mcekovic** [comment]
1. "Vs ..." filter is using rank, while seeds/entries are shown in Match description. Probably that is little confusing. Confusion will be less if there is filter by opponent seed too, will be added.
2. Seems like good idea.

**Comment by mcekovic** [comment]
Completed.
