### ISSUE TITLE
Jimmy  Connors activity : match missing (AO 1974)

### ISSUE THREAD

**Issue by Penseeeternelle** [mcekovic/tennis-crystal-ball#267]
According to UTS, Jimmy Connors has a 10 - 1 record at Australian Open. Round of 64 from 1974 edition is missing. Connors beat Chris Kachel (AUS) in straight sets, more detail :

http://www.atpworldtour.com/en/players/jimmy-connors/c044/player-activity?year=all&tournament=580

**Comment by mcekovic** [comment]
Also John McEnroe Wimbledon 1980 matches is wrong: 2 matches for R128, one won, one lost

**Comment by mcekovic** [comment]
Fixed
