### ISSUE TITLE
question about daily elo ranking updates

### ISSUE THREAD

**Issue by spyrop** [mcekovic/tennis-crystal-ball#268]
Is in project's plans to update elo rankings daily?
Would it be possible to provide daily results to your system?

**Comment by spyrop** [comment]
thank for the answer.
In tournament fourecasts, it would also be helpfull to have tournament't surface elo rating (or/and recent elo ratings).
By the way, is it possible to calculate daily surface-specific elo rating from current elo rating and weekly surface-specific elo rating?

**Comment by mcekovic** [comment]
Hi, all type of match Elo ratings in in-progress tournaments are now tracked as tournament goes and there is selector for Elo type from which one can choose: Overall, Recent, Surface, In / Out or Set Elo to be shown in tournament forecast pages.
These 5 Elo ratings types are then used in match prediction (along with other factors), but with different weights (depending on surface).
