### ISSUE TITLE
Connors career points

### ISSUE THREAD

**Issue by 9aaron** [mcekovic/tennis-crystal-ball#274]
http://www.ultimatetennisstatistics.com/statsLeaders says Jimmy Connors played 13039 points in his career. This can't be right as this is an average of 8 points per match. Sorry if this is a known issue but I can't see it as an open issue.

**Comment by mcekovic** [comment]
Sorry, but there is no Points data for matches before 1990 season, so Connors points data includes just a few seasons in his late career.
