### ISSUE TITLE
How to fix Elo rating?

### ISSUE THREAD

**Issue by jhzao82** [mcekovic/tennis-crystal-ball#294]
It looks like I miss a lot of date by Elo rating, I try many ways, but don't know to fix then.

Rank | Best Rank | Country | Name | +/- | Elo +/- | Elo Rating
-- | -- | -- | -- | -- | -- | --
1 CH | 1 | AUS | Rod Laver | - | - | CH 2382
2 | 1 | AUS | Ken Rosewall | - | - | 2364
3 CH | 3 | AUS | John Newcombe | - | - | CH 2269
4 CH | 4 | AUS | Tony Roche | - | - | CH 2223
5 | 3 | ESP | Andres Gimeno | - | - | 2188

**Comment by mcekovic** [comment]
Not sure I understand the problem, in the table above everything seems ok.
Please note that before Jun/July 1968, there are not enough matches for any usful Elo ranking list.

**Comment by mcekovic** [comment]
Data load for Elo ratings is fixed for DB schema created from scratch.
You need to recreate DB Schema and reload the data again.
Alternatively (and faster) you can make player_elo_ranking columns recent_rank and recent_elo_rating NULLABLE.

**Comment by mcekovic** [comment]
Did a full DB rebuild and data reload myself on development machine and fixed all errors, so you should be able to do so too.

**Comment by jhzao82** [comment]
I found same mistake, so I do some replace to csv data file, If I need to replace them?

sed -i 's/E Html> Pe Html>//g' atp_matches_futures_2015.csv
sed -i 's/>//g' atp_matches_qual_chall_2017.csv atp_rankings_10s.csv
sed -i 's/"bioTableWrap bioTableWrapAlt"">"//g' atp_rankings_00s.csv

**Comment by mcekovic** [comment]
UTS data loaders do not guarantee to work for challenger and futures files and have no workarounds for issues in these files.
For ATP ranking files, yes, you need to correct the files, and just remove the two erroneous rows:
atp_rankings_10s.csv containing >
atp_rankings_00s.csv containing bioTableWrap bioTableWrapAlt"

**Comment by mcekovic** [comment]
For the recent Andtwerp and Stockholm tournaments, there is an issue on the ATP web site, finals matches are missing. They used to be there a week ago, when UTS production site updated data. We just need to wait for ATP to fix it... Then you need to delete these two tournament events (DELETE FROM tournament_event WHERE tournament_event_id IN (?, ?);   ) and then run the overall delta update (-ln option in data load).

**Comment by jhzao82** [comment]
I will check that later. Thank you very much!
