### ISSUE TITLE
New completed Tournaments are not save.

### ISSUE THREAD

**Issue by jhzao82** [mcekovic/tennis-crystal-ball#310]
I remove tournaments in in-progress table, then run data-load with -ln, It can find new tournaments, But they can not displayed, There are Brisbane, Doha and Pune.

**Comment by mcekovic** [comment]
UTS web site caches most frequently used data (unless dev Spring profile is used).
There is data cache and Thymeleaf template cache.

If dev profile (application-dev.properties) is used, caching is disabled:
spring.cache.type=none
spring.thymeleaf.cache=false

In production, caching is enabled and cache is cleared by using data load command with parameter -cc.
