### ISSUE TITLE
Alex Mayer / Sandy Mayer

### ISSUE THREAD

**Issue by Amonkhan** [mcekovic/tennis-crystal-ball#322]
Hi! First of all thank you for your amazing work! Your site is incredible!
I've been exploring the GOAT list these days and I think I've noticed what might be a mistake. There is a player called Alex Mayer ranked 484 but after having checked both Wikipedia and the official ATP site I think this Alex Mayer is in fact Sandy Mayer (ranked 121). When he won the Birmingham tournament (1973) he was not nicknamed Sandy yet, but simply Alex, as his full first name is Alexander. So I think you should fuse the two profiles.. and add one point to Sandy by the way :-)
Thanks again! Have a good day!

**Comment by mcekovic** [comment]
Fixed
