### ISSUE TITLE
The forecasts of past tournaments dissapear.

### ISSUE THREAD

**Issue by LeVronYames** [mcekovic/tennis-crystal-ball#325]
For some reason, the forecasts of past tournaments dissapear of the page, which is dissapointing. For instance, it is impossible to check the forecasts given in the Australian Open 2019 and Roland-Garros 2019. It is interesting to maintain the forecasts of past tournaments, so users can check how many forecasts where correctly predicted by Ultimate Tennis Statistics.

**Comment by mcekovic** [comment]
Added
