### ISSUE TITLE
Women's tennis?

### ISSUE THREAD

**Issue by jtr13** [mcekovic/tennis-crystal-ball#333]
Would be great to have these stats on women's tennis as well.

**Comment by mcekovic** [comment]
Woman's tennis would be great, but not enough free time :(.

**Comment by mcekovic** [comment]
Duplicate of #289

**Comment by jtr13** [comment]
Get it, glad it's on the radar. I'd recommend making it more explicit though that it's a men's tennis site, as simple as adding one word here: "Welcome to Ultimate Tennis Statistics, the ultimate **men's** tennis statistics destination for the die-hard tennis fans!"

I spent some time looking for the women's stats. Great site, thanks for your work on it!
