### ISSUE TITLE
Archived Tournament Forecasts

### ISSUE THREAD

**Issue by EmbraceTheMadness** [mcekovic/tennis-crystal-ball#334]
Hi,

Great website! I have a question about the archived tournament forecasts. Are they archived as they were calculated at the time or have they been recompiled with updated data? I’ve been going through some of the early 2019 forecasts and they seem almost too good to be correct. Thanks!

**Comment by mcekovic** [comment]
Forecasts in 2019 before 17 July had a bug where matches in the current tournament influenced past predictions for the same tournament. This should not be the case after July 17-th.
See https://github.com/mcekovic/tennis-crystal-ball/issues/326

**Comment by EmbraceTheMadness** [comment]
Thanks. However, it looks like it affects some more recent tournaments as
well. One example is the Canada Masters.
