### ISSUE TITLE
Bug in results?

### ISSUE THREAD

**Issue by Jyrki** [mcekovic/tennis-crystal-ball#349]
If you check the H2H between players having done the ATP finals recently and you try to exclude their last encounter, you'll find that it was not entered at the right date. Example: Medvedev-Djokovic reacts like their last match was on 15-11-20 but it was not played on that day (source Flashscore if you doubt me). There are other examples.

BTW, this is an amazing website and I admire your work.

**Comment by mcekovic** [comment]
Hi,

I do not have data for the exact match dates, just for the start of the
tournaments.

MC

**Comment by Jyrki** [comment]
Thanks, I understand now.

**Comment by Jyrki** [comment]
Hmmm, for Medvedev-Zverev I just don't get when their encounters were put in the system. Their ATP Finals match is not related to the start of the tournament. And for their previous match a few days sooner (in Bercy), it's even more mysterious.
