### ISSUE TITLE
Quarter-Final Streaks count and Tour Finals

### ISSUE THREAD

**Issue by Penseeeternelle** [mcekovic/tennis-crystal-ball#358]
Hi, i was wondering the last time Rafa lost before the quarter-finals of a tournament. And surprised not to see his current streak on the top list since it happened for the last time in 2019. 
UTS ends a quarter-final streak when a player has lost in the round robin stage at the Tour Finals. It shouldn't, right ?

Keep up the great work !

**Comment by mcekovic** [comment]
Could you tell me exactly which page is this about, is it about the Player
Profile's Matches, Events or Streaks page?

**Comment by mcekovic** [comment]
Could you tell me exactly which page is this about, is it about the Player Profile's Matches, Events or Streaks page?

**Comment by Penseeeternelle** [comment]
It's about the record page "Quarter-Final streak" [https://www.ultimatetennisstatistics.com/record?recordId=QuarterFinalStreak].

I just checked:
* In the player events page, by picking QF+: [https://www.ultimatetennisstatistics.com/playerProfile?playerId=4742&tab=events&result=QF%2B] it does not include the Tour Final tournament.
* In the player matches page, by picking QF+: [https://www.ultimatetennisstatistics.com/playerProfile?playerId=4742&tab=matches&result=QF%2B] it does include the Tour Final matches. 

So it's looks like a "tournament problem" not a "match problem". It's related to the record pages, the player event pages, not player match pages nor player streak pages.

**Comment by mcekovic** [comment]
Thanks for the detailed information.
But I think it works like it should. If a player lost in the RR phase of
the Tour Finals, he/she did not reach QF+ phase. So in the Records and
Player Events page, when selecting QF+, events where the player did not
pass RR stage should not be counted.
In the Player Matches page QF+ filter should include only SF and F matches,
not RR matches.

Regards,
Mileta

**Comment by mcekovic** [comment]
P. S. RR is not something that is before SF, it is something that is before
KO (knock-out) rounds. Thus RR is always before all KO rounds, including QF
(if it is present as KO round).
There were RR tournaments in the past that had QF or even R16 included in
the KO phase (like the old Davis Cup from a couple of years ago), as well
as there were some tournaments with only F as the KO phase.

**Comment by Penseeeternelle** [comment]
There are several ways to understand/see it. Thx for detailing, i got yours :)
I was thinking it in terms of QF = 8 players remaining. So for me, being qualified for the ATP Finals means a QF, as it could be the case for a classic single elimination tournament with 8 participants.
You do consider the Round Robin as a "preliminary stage" which makes sense !
It's a pity for Rafa ^^ but i guess you're more a Nole fan :p.

Without transition, Federer miss a match on hard. According to UTS he's 776-156 on hard but it's actually 783-156. (You do not record Laver Cup whichin Federer is 6-0, so there is still one victory missing.
I search a bit it's during the year 2014. The UTS yearly total is correct (73-12), but summing all surfaces you got 72-12: (hard 55-7, clay 8-4, grass 9-1.

The error is related to the player profile, performance and matches tabs:
* [https://www.ultimatetennisstatistics.com/playerProfile?playerId=3819&tab=matches&season=2014&surface=H](url) 
* [https://www.ultimatetennisstatistics.com/playerProfile?playerId=3819&tab=performance&season=2014](url)
* [https://www.ultimatetennisstatistics.com/playerProfile?playerId=3819](url)
You're missing the first round Davis Cup match against Serbia (Ilija Bozoljac): [https://www.atptour.com/en/players/roger-federer/f324/player-activity?year=2014](url)

The weird thing is UTS got the correct total for Roger Davis Cup match (40-8).

**Comment by mcekovic** [comment]
Thanks for raising the issue about the Federer match. It is actually in the
UTS database, but with no specified surface:
https://www.ultimatetennisstatistics.com/playerProfile?playerId=3819&level=D&tab=matches&season=2014
That is why total is correct, but sum by surface is not.
