### ISSUE TITLE
Huge missing data update

### ISSUE THREAD

**Issue by Fedal365** [mcekovic/tennis-crystal-ball#359]
You mention on the UTS website that you have done a Huge missing data update: More than 200 tournament events are added in seasons 1968-1972.

Has this also been done to the Github DB?

Thanks, Tom

**Comment by mcekovic** [comment]
GitHub repo is maintained by Jeff Sckamann. I have told him that ATP has
added these tournaments on its official website so he is aware, but did not
check if he included them (I suppose if not it will be relatively soon).

Regards,
Mileta
