### ISSUE TITLE
Will the wimbledon match stats be added?

### ISSUE THREAD

**Issue by paulsteidomeyer** [mcekovic/tennis-crystal-ball#361]
Wimbledon 2021 is missing match stats:

https://www.ultimatetennisstatistics.com/tournamentEvent?tournamentEventId=4489

But I see that the stats are available at FlashScore:

https://www.flashscore.co.uk/tennis/atp-singles/wimbledon/

I'm wondering if you're still planning on adding the match stats? Thanks!

**Comment by mcekovic** [comment]
Included
