### ISSUE TITLE
Djokovic lost matches after winning or losing 1st set seem wrong

### ISSUE THREAD

**Issue by mcekovic** [mcekovic/tennis-crystal-ball#371]
How is it possible that Djokovic has better win percentage than Nadal both after winning or losing the first set but he has worst overall win percentage? That can’t make any sense, he either has to have worse percentage after winning the first set or after losing it, because overall he hasn’t won as many games percentages as Nadal.

**Comment by xavikortes** [comment]
It seems to be correct. :+1: 

![Captura de pantalla de 2022-06-06 18-35-32](https://user-images.githubusercontent.com/9928629/172205081-8261d7eb-5559-42b6-aa0d-a9eee05d486b.png)

**Comment by ghost** [comment]
This is an example of Simpson's paradox in statistical term. Feel free to check out more here: https://en.wikipedia.org/wiki/Simpson%27s_paradox
