### ISSUE TITLE
Top Performers View Filter Issue

### ISSUE THREAD

**Issue by SrijanKhare** [mcekovic/tennis-crystal-ball#379]
In the Top Performers view (https://www.ultimatetennisstatistics.com/topPerformers), I have put the following filters

- Tournament Level: Big
- Opponent: Elo > 2400
- Min Entries: 15
- Category: Tie-Breaks

With those filters, we can see that the view shows Federer has 28 total matches, however, when you click on the number it brings up Federer's player view with the same filters. The issue is that with the same filters the player view shows 21 total matches while the Top Performers view shows 28 total matches. 

Seems like the issue is rooted in either of these two places:  https://github.com/mcekovic/tennis-crystal-ball/blob/master/tennis-stats/src/main/java/org/strangeforest/tcb/stats/service/TopPerformersView.java
or 
https://github.com/mcekovic/tennis-crystal-ball/blob/b4b602e0eeea8365839fee7500d8b1248f186be0/tennis-stats/src/main/resources/templates/topPerformers.html

Maybe the category is not being set correctly?

**Comment by mcekovic** [comment]
When Category is 'Tie Breaks', in Top Performers Played columns is number
of Tie Breaks, not number of matches.
MC

**Comment by SrijanKhare** [comment]
ah okay, makes sense!
